# Generated by Django 3.2.7 on 2021-10-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postcommentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcommentmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
