# Generated by Django 3.2.7 on 2021-10-20 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postcommentmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcommentmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.postmodel', verbose_name='post'),
        ),
    ]
