# Generated by Django 3.2.7 on 2021-10-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownermodel',
            name='image',
            field=models.ImageField(null=True, upload_to='media/owners', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='ownermodel',
            name='full_name',
            field=models.CharField(max_length=56, verbose_name='full name'),
        ),
        migrations.AlterField(
            model_name='ownermodel',
            name='occupation',
            field=models.CharField(max_length=56, verbose_name='occupation'),
        ),
    ]
