# Generated by Django 3.2.7 on 2021-10-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20211020_1739'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OwnerModel',
        ),
    ]
