# Generated by Django 3.2.7 on 2021-10-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20211014_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='real_price',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='price',
            field=models.FloatField(default=0, verbose_name='price'),
        ),
    ]
