# Generated by Django 3.2.7 on 2021-10-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_wishlistmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlistmodel',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='wishlistmodel',
            unique_together=set(),
        ),
    ]
