# Generated by Django 3.2.7 on 2021-10-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20211020_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='main',
            field=models.CharField(max_length=16, null=True, verbose_name='main'),
        ),
        migrations.AddField(
            model_name='colormodel',
            name='main',
            field=models.CharField(max_length=16, null=True, verbose_name='main'),
        ),
        migrations.AddField(
            model_name='producttagmodel',
            name='main',
            field=models.CharField(max_length=16, null=True, verbose_name='main'),
        ),
    ]
