# Generated by Django 3.2.7 on 2021-10-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20211020_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='main',
        ),
        migrations.RemoveField(
            model_name='colormodel',
            name='main',
        ),
        migrations.RemoveField(
            model_name='producttagmodel',
            name='main',
        ),
        migrations.AddField(
            model_name='producttagmodel',
            name='title_en',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='producttagmodel',
            name='title_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='producttagmodel',
            name='title_uz',
            field=models.CharField(max_length=32, null=True, verbose_name='title'),
        ),
    ]
