# Generated by Django 3.2.7 on 2021-10-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20211021_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='products.productmodel'),
        ),
    ]
